<?xml version="1.0" encoding="UTF-8"?>
<!-- You may freely edit this file. See commented blocks below for -->
<!-- some examples of how to customize the build. -->
<!-- (If you delete it and reopen the project it will be recreated.) -->
<!-- By default, only the Clean and Build commands use this build script. -->
<!-- Commands such as Run, Debug, and Test only use this build script if -->
<!-- the Compile on Save feature is turned off for the project. -->
<!-- You can turn off the Compile on Save (or Deploy on Save) setting -->
<!-- in the project's Project Properties dialog box.-->
<project name="OLC1_Proyecto1_201403888" default="default" basedir=".">
    <description>Builds, tests, and runs the project OLC1_Proyecto1_201403888.</description>
    <import file="nbproject/build-impl.xml"/>
   
    
    <target name="-pre-compile">

    <echo message="========== Generando Lexer con JFlex =========="/>

    <taskdef
        name="jflex"
        classname="jflex.anttask.JFlexTask"
        classpath="${file.reference.jflex-full-1.9.1.jar}"
    />

    <jflex
        file="${basedir}/src/analizadores/Lexer.flex"
        outdir="${basedir}/src/analizadores"
        verbose="true"
    />
    
     <!-- ============================= -->
    <!-- GENERAR PARSER CON CUP -->
    <!-- ============================= -->

    <echo message="========== Generando Parser con CUP =========="/>

    <java
        classname="java_cup.Main"
        fork="true"
        failonerror="true"
    >

        <classpath>
            <pathelement location="${file.reference.java-cup-11b.jar}"/>
            <pathelement location="${file.reference.java-cup-runtime-11b.jar}"/>
        </classpath>

        <arg value="-parser"/>
        <arg value="Parser"/>

        <arg value="-symbols"/>
        <arg value="sym"/>

        <arg value="-destdir"/>
        <arg value="${basedir}/src/analizadores"/>

        <arg value="${basedir}/src/analizadores/Parser.cup"/>

    </java>

    </target>
</project>
