// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/Usuario/Documents/NetBeansProjects/OLC1_Proyecto1_201403888/src/analizadores/Lexer.flex

package analizadores;

import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\4\0\1\5\1\0\1\6\1\7\1\10\1\0\1\11"+
    "\1\0\1\12\1\13\12\14\1\15\1\0\1\16\1\17"+
    "\1\20\2\0\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\32\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\32\1\46\1\32\1\47\1\0\1\50\1\0\1\51"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\2\32\1\63\1\64\1\65\1\66\1\67"+
    "\1\32\1\70\1\71\1\72\1\73\1\74\1\75\1\32"+
    "\1\76\1\32\1\77\1\100\1\101\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\1\1\11\10\12\1\13\1\14"+
    "\20\12\1\15\1\1\1\16\1\17\1\20\1\0\1\2"+
    "\1\0\1\21\1\22\1\23\1\24\17\12\1\25\21\12"+
    "\1\26\1\0\1\27\32\12\1\30\11\12\1\2\6\12"+
    "\1\31\5\12\1\32\6\12\1\33\1\34\7\12\1\35"+
    "\2\12\1\36\3\12\1\37\7\12\1\40\13\12\1\41"+
    "\4\12\1\42\32\12\1\43\1\12\1\44\17\12\1\45"+
    "\1\46\5\12\1\47\4\12\1\50\1\12\1\51\7\12"+
    "\1\52\1\12\1\53\3\12\1\54\4\12\1\55\30\12"+
    "\1\56\27\12\1\57\7\12\1\60\4\12\1\61\20\12"+
    "\1\62\6\12\1\63\1\64\1\12\1\65\1\66\12\12"+
    "\1\67\1\70\2\12\1\71\2\12\1\72\3\12\1\73"+
    "\6\12\1\74\1\12\1\75\1\76\10\12\1\77\4\12"+
    "\1\100\2\12\1\101\5\12\1\102\2\12\1\103\5\12"+
    "\1\104\1\105\3\12\1\106\1\107\4\12\1\110\1\111";

  private static int [] zzUnpackAction() {
    int [] result = new int[430];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\102\0\102\0\102"+
    "\0\u014a\0\u018c\0\102\0\u01ce\0\u0210\0\u0252\0\u0294\0\u02d6"+
    "\0\u0318\0\u035a\0\u039c\0\u03de\0\u0420\0\u0462\0\102\0\102"+
    "\0\u04a4\0\u04e6\0\u0528\0\u056a\0\u05ac\0\u05ee\0\u0630\0\u0672"+
    "\0\u06b4\0\u06f6\0\u0738\0\u077a\0\u07bc\0\u07fe\0\u0840\0\u0882"+
    "\0\102\0\u08c4\0\102\0\102\0\102\0\u0906\0\u0948\0\u098a"+
    "\0\u09cc\0\102\0\102\0\102\0\u0a0e\0\u0a50\0\u0a92\0\u0ad4"+
    "\0\u0b16\0\u0b58\0\u0b9a\0\u0bdc\0\u0c1e\0\u0c60\0\u0ca2\0\u0ce4"+
    "\0\u0d26\0\u0d68\0\u0daa\0\u02d6\0\u0dec\0\u0e2e\0\u0e70\0\u0eb2"+
    "\0\u0ef4\0\u0f36\0\u0f78\0\u0fba\0\u0ffc\0\u103e\0\u1080\0\u10c2"+
    "\0\u1104\0\u1146\0\u1188\0\u11ca\0\u120c\0\102\0\u124e\0\u098a"+
    "\0\u1290\0\u12d2\0\u1314\0\u1356\0\u1398\0\u13da\0\u141c\0\u145e"+
    "\0\u14a0\0\u14e2\0\u1524\0\u1566\0\u15a8\0\u15ea\0\u162c\0\u166e"+
    "\0\u16b0\0\u16f2\0\u1734\0\u1776\0\u17b8\0\u17fa\0\u183c\0\u187e"+
    "\0\u18c0\0\u1902\0\u02d6\0\u1944\0\u1986\0\u19c8\0\u1a0a\0\u1a4c"+
    "\0\u1a8e\0\u1ad0\0\u1b12\0\u1b54\0\102\0\u1b96\0\u1bd8\0\u1c1a"+
    "\0\u1c5c\0\u1c9e\0\u1ce0\0\u02d6\0\u1d22\0\u1d64\0\u1da6\0\u1de8"+
    "\0\u1e2a\0\u02d6\0\u1e6c\0\u1eae\0\u1ef0\0\u1f32\0\u1f74\0\u1fb6"+
    "\0\u1ff8\0\u02d6\0\u203a\0\u207c\0\u20be\0\u2100\0\u2142\0\u2184"+
    "\0\u21c6\0\u02d6\0\u2208\0\u224a\0\u02d6\0\u228c\0\u22ce\0\u2310"+
    "\0\u02d6\0\u2352\0\u2394\0\u23d6\0\u2418\0\u245a\0\u249c\0\u24de"+
    "\0\u02d6\0\u2520\0\u2562\0\u25a4\0\u25e6\0\u2628\0\u266a\0\u26ac"+
    "\0\u26ee\0\u2730\0\u2772\0\u27b4\0\u02d6\0\u27f6\0\u2838\0\u287a"+
    "\0\u28bc\0\u02d6\0\u28fe\0\u2940\0\u2982\0\u29c4\0\u2a06\0\u2a48"+
    "\0\u2a8a\0\u2acc\0\u2b0e\0\u2b50\0\u2b92\0\u2bd4\0\u2c16\0\u2c58"+
    "\0\u2c9a\0\u2cdc\0\u2d1e\0\u2d60\0\u2da2\0\u2de4\0\u2e26\0\u2e68"+
    "\0\u2eaa\0\u2eec\0\u2f2e\0\u2f70\0\u02d6\0\u2fb2\0\u02d6\0\u2ff4"+
    "\0\u3036\0\u3078\0\u30ba\0\u30fc\0\u313e\0\u3180\0\u31c2\0\u3204"+
    "\0\u3246\0\u3288\0\u32ca\0\u330c\0\u334e\0\u3390\0\u02d6\0\u02d6"+
    "\0\u33d2\0\u3414\0\u3456\0\u3498\0\u34da\0\u02d6\0\u351c\0\u355e"+
    "\0\u35a0\0\u35e2\0\u02d6\0\u3624\0\u02d6\0\u3666\0\u36a8\0\u36ea"+
    "\0\u372c\0\u376e\0\u37b0\0\u37f2\0\u3834\0\u3876\0\u02d6\0\u38b8"+
    "\0\u38fa\0\u393c\0\u02d6\0\u397e\0\u39c0\0\u3a02\0\u3a44\0\u3a86"+
    "\0\u3ac8\0\u3b0a\0\u3b4c\0\u3b8e\0\u3bd0\0\u3c12\0\u3c54\0\u3c96"+
    "\0\u3cd8\0\u3d1a\0\u3d5c\0\u3d9e\0\u3de0\0\u3e22\0\u3e64\0\u3ea6"+
    "\0\u3ee8\0\u3f2a\0\u3f6c\0\u3fae\0\u3ff0\0\u4032\0\u4074\0\u40b6"+
    "\0\u02d6\0\u40f8\0\u413a\0\u417c\0\u41be\0\u4200\0\u4242\0\u4284"+
    "\0\u42c6\0\u4308\0\u434a\0\u438c\0\u43ce\0\u4410\0\u4452\0\u4494"+
    "\0\u44d6\0\u4518\0\u455a\0\u459c\0\u45de\0\u4620\0\u4662\0\u46a4"+
    "\0\u46e6\0\u4728\0\u476a\0\u47ac\0\u47ee\0\u4830\0\u4872\0\u48b4"+
    "\0\u02d6\0\u48f6\0\u4938\0\u497a\0\u49bc\0\u02d6\0\u49fe\0\u4a40"+
    "\0\u4a82\0\u4ac4\0\u4b06\0\u4b48\0\u4b8a\0\u4bcc\0\u4c0e\0\u4c50"+
    "\0\u4c92\0\u4cd4\0\u4d16\0\u4d58\0\u4d9a\0\u4ddc\0\u02d6\0\u4e1e"+
    "\0\u4e60\0\u4ea2\0\u4ee4\0\u4f26\0\u4f68\0\u02d6\0\u02d6\0\u4faa"+
    "\0\u02d6\0\u02d6\0\u4fec\0\u502e\0\u5070\0\u50b2\0\u50f4\0\u5136"+
    "\0\u5178\0\u51ba\0\u51fc\0\u523e\0\u02d6\0\u02d6\0\u5280\0\u52c2"+
    "\0\u02d6\0\u5304\0\u5346\0\u02d6\0\u5388\0\u53ca\0\u540c\0\u02d6"+
    "\0\u544e\0\u5490\0\u54d2\0\u5514\0\u5556\0\u5598\0\u02d6\0\u55da"+
    "\0\u02d6\0\u561c\0\u565e\0\u56a0\0\u56e2\0\u5724\0\u5766\0\u57a8"+
    "\0\u57ea\0\u582c\0\u02d6\0\u586e\0\u58b0\0\u58f2\0\u5934\0\u02d6"+
    "\0\u5976\0\u59b8\0\u02d6\0\u59fa\0\u5a3c\0\u5a7e\0\u5ac0\0\u5b02"+
    "\0\u02d6\0\u5b44\0\u5b86\0\u02d6\0\u5bc8\0\u5c0a\0\u5c4c\0\u5c8e"+
    "\0\u5cd0\0\u02d6\0\u02d6\0\u5d12\0\u5d54\0\u5d96\0\u02d6\0\u02d6"+
    "\0\u5dd8\0\u5e1a\0\u5e5c\0\u5e9e\0\u02d6\0\u02d6";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[430];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\2"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\4\20\1\21\1\20\1\22\4\20\1\23\2\20"+
    "\1\24\1\25\3\20\1\26\1\20\1\27\1\30\2\20"+
    "\1\31\1\20\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\20\1\42\1\43\1\44\1\45\1\46"+
    "\1\20\1\47\1\50\1\20\1\51\1\52\1\53\103\0"+
    "\2\3\116\0\1\54\67\0\1\55\104\0\1\56\2\0"+
    "\1\57\100\0\1\60\1\0\1\12\4\0\26\61\2\0"+
    "\26\61\22\0\1\62\101\0\1\63\101\0\1\64\76\0"+
    "\1\20\4\0\17\20\1\65\6\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\26\20\17\0\1\20\4\0"+
    "\10\20\1\66\15\20\2\0\26\20\17\0\1\20\4\0"+
    "\4\20\1\67\21\20\2\0\26\20\17\0\1\20\4\0"+
    "\1\70\3\20\1\71\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\4\20\1\72\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\7\20\1\73\3\20\1\74\12\20\2\0\26\20"+
    "\17\0\1\20\4\0\1\75\25\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\15\20\1\76\10\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\77\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\12\20\1\100\13\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\101\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\102\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\103\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\6\20\1\104\5\20\1\105"+
    "\11\20\17\0\1\20\4\0\26\20\2\0\1\20\1\106"+
    "\13\20\1\107\10\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\20\1\110\24\20\17\0\1\20\4\0\26\20\2\0"+
    "\16\20\1\111\7\20\17\0\1\20\4\0\26\20\2\0"+
    "\12\20\1\112\13\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\20\1\113\13\20\1\114\4\20\1\115\3\20\17\0"+
    "\1\20\4\0\26\20\2\0\3\20\1\116\1\20\1\117"+
    "\14\20\1\120\3\20\17\0\1\20\4\0\26\20\2\0"+
    "\10\20\1\121\4\20\1\122\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\11\20\1\123\14\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\20\1\124\7\20\1\125\14\20\103\0"+
    "\1\126\1\0\10\56\1\127\71\56\2\57\2\0\76\57"+
    "\14\0\1\130\101\0\1\61\4\0\26\61\2\0\26\61"+
    "\17\0\1\20\4\0\2\20\1\131\23\20\2\0\26\20"+
    "\17\0\1\20\4\0\17\20\1\132\6\20\2\0\26\20"+
    "\17\0\1\20\4\0\1\133\25\20\2\0\26\20\17\0"+
    "\1\20\4\0\6\20\1\134\17\20\2\0\26\20\17\0"+
    "\1\20\4\0\3\20\1\135\22\20\2\0\26\20\17\0"+
    "\1\20\4\0\20\20\1\136\5\20\2\0\26\20\17\0"+
    "\1\20\4\0\10\20\1\137\15\20\2\0\26\20\17\0"+
    "\1\20\4\0\1\140\25\20\2\0\26\20\17\0\1\20"+
    "\4\0\17\20\1\141\6\20\2\0\26\20\17\0\1\20"+
    "\4\0\26\20\2\0\14\20\1\142\11\20\17\0\1\20"+
    "\4\0\26\20\2\0\13\20\1\143\12\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\144\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\11\20\1\145\14\20\17\0\1\20"+
    "\4\0\26\20\2\0\21\20\1\146\4\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\20\1\147\24\20\17\0\1\20"+
    "\4\0\26\20\2\0\11\20\1\150\14\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\151\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\24\20\1\152\1\20\17\0\1\20"+
    "\4\0\26\20\2\0\7\20\1\153\1\20\1\154\7\20"+
    "\1\155\4\20\17\0\1\20\4\0\26\20\2\0\16\20"+
    "\1\156\7\20\17\0\1\20\4\0\26\20\2\0\1\20"+
    "\1\157\24\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\160\11\20\17\0\1\20\4\0\26\20\2\0\22\20"+
    "\1\161\3\20\17\0\1\20\4\0\26\20\2\0\12\20"+
    "\1\162\1\20\1\163\11\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\164\10\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\165\4\20\1\166\13\20\17\0\1\20"+
    "\4\0\26\20\2\0\3\20\1\167\22\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\170\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\21\20\1\171\4\20\17\0\1\20"+
    "\4\0\26\20\2\0\3\20\1\172\22\20\17\0\1\20"+
    "\4\0\26\20\2\0\17\20\1\173\6\20\17\0\1\20"+
    "\4\0\26\20\2\0\21\20\1\174\4\20\3\0\10\56"+
    "\1\127\2\56\1\175\66\56\14\0\1\20\4\0\1\176"+
    "\25\20\2\0\26\20\17\0\1\20\4\0\4\20\1\177"+
    "\21\20\2\0\26\20\17\0\1\20\4\0\13\20\1\200"+
    "\7\20\1\201\2\20\2\0\26\20\17\0\1\20\4\0"+
    "\10\20\1\202\15\20\2\0\26\20\17\0\1\20\4\0"+
    "\10\20\1\203\15\20\2\0\26\20\17\0\1\20\4\0"+
    "\21\20\1\204\4\20\2\0\26\20\17\0\1\20\4\0"+
    "\4\20\1\205\21\20\2\0\26\20\17\0\1\20\4\0"+
    "\20\20\1\206\5\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\207\25\20\17\0\1\20\4\0\26\20"+
    "\2\0\22\20\1\210\3\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\20\1\211\24\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\212\20\20\17\0\1\20\4\0\26\20"+
    "\2\0\12\20\1\213\13\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\214\25\20\17\0\1\20\4\0\26\20\2\0"+
    "\12\20\1\215\13\20\17\0\1\20\4\0\26\20\2\0"+
    "\21\20\1\216\4\20\17\0\1\20\4\0\26\20\2\0"+
    "\21\20\1\217\4\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\220\25\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\221\20\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\222\11\20\17\0\1\20\4\0\26\20\2\0\3\20"+
    "\1\223\22\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\224\10\20\17\0\1\20\4\0\26\20\2\0\25\20"+
    "\1\225\17\0\1\20\4\0\26\20\2\0\4\20\1\226"+
    "\21\20\17\0\1\20\4\0\26\20\2\0\14\20\1\227"+
    "\11\20\17\0\1\20\4\0\26\20\2\0\5\20\1\230"+
    "\20\20\17\0\1\20\4\0\26\20\2\0\17\20\1\231"+
    "\6\20\17\0\1\20\4\0\26\20\2\0\4\20\1\232"+
    "\21\20\17\0\1\20\4\0\26\20\2\0\6\20\1\233"+
    "\17\20\17\0\1\20\4\0\26\20\2\0\3\20\1\234"+
    "\22\20\17\0\1\20\4\0\26\20\2\0\14\20\1\235"+
    "\11\20\17\0\1\20\4\0\26\20\2\0\1\20\1\236"+
    "\24\20\17\0\1\20\4\0\26\20\2\0\21\20\1\237"+
    "\4\20\17\0\1\20\4\0\26\20\2\0\17\20\1\240"+
    "\6\20\17\0\1\20\4\0\26\20\2\0\10\20\1\241"+
    "\15\20\17\0\1\20\4\0\15\20\1\242\10\20\2\0"+
    "\26\20\17\0\1\20\4\0\1\20\1\243\24\20\2\0"+
    "\26\20\17\0\1\20\4\0\10\20\1\244\15\20\2\0"+
    "\26\20\17\0\1\20\4\0\25\20\1\245\2\0\26\20"+
    "\17\0\1\20\4\0\2\20\1\246\23\20\2\0\26\20"+
    "\17\0\1\20\4\0\21\20\1\247\4\20\2\0\26\20"+
    "\17\0\1\20\4\0\13\20\1\250\12\20\2\0\26\20"+
    "\17\0\1\20\4\0\7\20\1\251\16\20\2\0\26\20"+
    "\17\0\1\20\4\0\2\20\1\252\23\20\2\0\26\20"+
    "\17\0\1\20\4\0\26\20\2\0\20\20\1\253\5\20"+
    "\17\0\1\20\4\0\26\20\2\0\7\20\1\254\16\20"+
    "\17\0\1\20\4\0\26\20\2\0\5\20\1\255\20\20"+
    "\17\0\1\20\4\0\26\20\2\0\12\20\1\256\1\257"+
    "\12\20\17\0\1\20\4\0\26\20\2\0\11\20\1\260"+
    "\14\20\17\0\1\20\4\0\26\20\2\0\11\20\1\261"+
    "\14\20\17\0\1\20\4\0\26\20\2\0\1\262\25\20"+
    "\17\0\1\20\4\0\26\20\2\0\10\20\1\263\15\20"+
    "\17\0\1\20\4\0\26\20\2\0\1\264\25\20\17\0"+
    "\1\20\4\0\26\20\2\0\10\20\1\265\15\20\17\0"+
    "\1\20\4\0\26\20\2\0\14\20\1\266\11\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\267\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\15\20\1\270\10\20\17\0"+
    "\1\20\4\0\26\20\2\0\4\20\1\271\21\20\17\0"+
    "\1\20\4\0\26\20\2\0\20\20\1\272\5\20\17\0"+
    "\1\20\4\0\26\20\2\0\11\20\1\273\14\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\274\25\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\275\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\12\20\1\276\13\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\277\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\11\20\1\300\14\20\17\0\1\20"+
    "\4\0\4\20\1\301\21\20\2\0\26\20\17\0\1\20"+
    "\4\0\1\302\25\20\2\0\26\20\17\0\1\20\4\0"+
    "\15\20\1\303\10\20\2\0\26\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\304\25\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\305\25\20\17\0\1\20\4\0\1\306\25\20"+
    "\2\0\26\20\17\0\1\20\4\0\3\20\1\307\22\20"+
    "\2\0\26\20\17\0\1\20\4\0\17\20\1\310\6\20"+
    "\2\0\26\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\311\20\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\312\20\20\17\0\1\20\4\0\26\20\2\0\4\20"+
    "\1\313\21\20\17\0\1\20\4\0\26\20\2\0\1\20"+
    "\1\314\24\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\315\10\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\316\11\20\17\0\1\20\4\0\26\20\2\0\1\20"+
    "\1\317\24\20\17\0\1\20\4\0\26\20\2\0\13\20"+
    "\1\320\12\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\321\20\20\17\0\1\20\4\0\26\20\2\0\3\20"+
    "\1\322\22\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\323\20\20\17\0\1\20\4\0\26\20\2\0\17\20"+
    "\1\324\6\20\17\0\1\20\4\0\26\20\2\0\13\20"+
    "\1\325\12\20\17\0\1\20\4\0\26\20\2\0\1\326"+
    "\17\20\1\327\5\20\17\0\1\20\4\0\26\20\2\0"+
    "\14\20\1\330\11\20\17\0\1\20\4\0\26\20\2\0"+
    "\10\20\1\331\6\20\1\332\1\333\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\334\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\335\25\20\17\0\1\20\4\0"+
    "\26\20\2\0\17\20\1\336\6\20\17\0\1\20\4\0"+
    "\26\20\2\0\15\20\1\337\10\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\340\25\20\17\0\1\20\4\0\13\20"+
    "\1\341\12\20\2\0\26\20\17\0\1\20\4\0\6\20"+
    "\1\342\17\20\2\0\26\20\17\0\1\20\4\0\20\20"+
    "\1\343\5\20\2\0\26\20\17\0\1\20\4\0\1\20"+
    "\1\344\24\20\2\0\26\20\17\0\1\20\4\0\21\20"+
    "\1\345\4\20\2\0\26\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\346\25\20\17\0\1\20\4\0\25\20\1\347"+
    "\2\0\26\20\17\0\1\20\4\0\26\20\2\0\20\20"+
    "\1\350\5\20\17\0\1\20\4\0\26\20\2\0\1\351"+
    "\25\20\17\0\1\20\4\0\26\20\2\0\1\352\25\20"+
    "\17\0\1\20\4\0\26\20\2\0\20\20\1\353\5\20"+
    "\17\0\1\20\4\0\26\20\2\0\23\20\1\354\2\20"+
    "\17\0\1\20\4\0\26\20\2\0\7\20\1\355\16\20"+
    "\17\0\1\20\4\0\26\20\2\0\12\20\1\356\13\20"+
    "\17\0\1\20\4\0\26\20\2\0\15\20\1\357\10\20"+
    "\17\0\1\20\4\0\26\20\2\0\1\20\1\360\24\20"+
    "\17\0\1\20\4\0\26\20\2\0\15\20\1\361\10\20"+
    "\17\0\1\20\4\0\26\20\2\0\14\20\1\362\11\20"+
    "\17\0\1\20\4\0\26\20\2\0\20\20\1\363\5\20"+
    "\17\0\1\20\4\0\26\20\2\0\14\20\1\364\11\20"+
    "\17\0\1\20\4\0\26\20\2\0\7\20\1\365\16\20"+
    "\17\0\1\20\4\0\26\20\2\0\5\20\1\366\3\20"+
    "\1\367\14\20\17\0\1\20\4\0\26\20\2\0\5\20"+
    "\1\370\20\20\17\0\1\20\4\0\26\20\2\0\3\20"+
    "\1\371\22\20\17\0\1\20\4\0\26\20\2\0\20\20"+
    "\1\372\5\20\17\0\1\20\4\0\26\20\2\0\17\20"+
    "\1\373\6\20\17\0\1\20\4\0\26\20\2\0\25\20"+
    "\1\374\17\0\1\20\4\0\26\20\2\0\17\20\1\375"+
    "\6\20\17\0\1\20\4\0\1\20\1\376\24\20\2\0"+
    "\26\20\17\0\1\20\4\0\13\20\1\377\12\20\2\0"+
    "\26\20\17\0\1\20\4\0\26\20\2\0\1\u0100\25\20"+
    "\17\0\1\20\4\0\21\20\1\u0101\4\20\2\0\26\20"+
    "\17\0\1\20\4\0\1\u0102\25\20\2\0\26\20\17\0"+
    "\1\20\4\0\4\20\1\u0103\21\20\2\0\26\20\17\0"+
    "\1\20\4\0\1\20\1\u0104\24\20\2\0\26\20\17\0"+
    "\1\20\4\0\26\20\2\0\16\20\1\u0105\7\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\20\1\u0106\24\20\17\0"+
    "\1\20\4\0\26\20\2\0\21\20\1\u0107\4\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\u0108\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\1\u0109\25\20\17\0\1\20"+
    "\4\0\26\20\2\0\23\20\1\u010a\2\20\17\0\1\20"+
    "\4\0\26\20\2\0\12\20\1\u010b\13\20\17\0\1\20"+
    "\4\0\26\20\2\0\13\20\1\u010c\12\20\17\0\1\20"+
    "\4\0\26\20\2\0\21\20\1\u010d\4\20\17\0\1\20"+
    "\4\0\26\20\2\0\22\20\1\u010e\3\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\20\1\u010f\24\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u0110\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u0111\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\u0112\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\6\20\1\u0113\17\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\u0114\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\u0115\25\20\17\0\1\20\4\0"+
    "\26\20\2\0\1\u0116\25\20\17\0\1\20\4\0\16\20"+
    "\1\u0117\7\20\2\0\26\20\17\0\1\20\4\0\17\20"+
    "\1\u0118\6\20\2\0\26\20\17\0\1\20\4\0\17\20"+
    "\1\u0119\6\20\2\0\26\20\17\0\1\20\4\0\17\20"+
    "\1\u011a\6\20\2\0\26\20\17\0\1\20\4\0\13\20"+
    "\1\u011b\12\20\2\0\26\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\u011c\10\20\17\0\1\20\4\0\26\20"+
    "\2\0\3\20\1\u011d\22\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\u011e\25\20\17\0\1\20\4\0\26\20\2\0"+
    "\20\20\1\u011f\5\20\17\0\1\20\4\0\26\20\2\0"+
    "\16\20\1\u0120\7\20\17\0\1\20\4\0\26\20\2\0"+
    "\5\20\1\u0121\20\20\17\0\1\20\4\0\26\20\2\0"+
    "\21\20\1\u0122\4\20\17\0\1\20\4\0\26\20\2\0"+
    "\2\20\1\u0123\23\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\u0124\25\20\17\0\1\20\4\0\26\20\2\0\13\20"+
    "\1\u0125\12\20\17\0\1\20\4\0\26\20\2\0\12\20"+
    "\1\u0126\13\20\17\0\1\20\4\0\26\20\2\0\21\20"+
    "\1\u0127\4\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\u0128\10\20\17\0\1\20\4\0\26\20\2\0\17\20"+
    "\1\u0129\6\20\17\0\1\20\4\0\26\20\2\0\22\20"+
    "\1\u012a\3\20\17\0\1\20\4\0\26\20\2\0\22\20"+
    "\1\u012b\3\20\17\0\1\20\4\0\26\20\2\0\2\20"+
    "\1\u012c\23\20\17\0\1\20\4\0\26\20\2\0\3\20"+
    "\1\u012d\22\20\17\0\1\20\4\0\13\20\1\u012e\12\20"+
    "\2\0\26\20\17\0\1\20\4\0\22\20\1\u012f\3\20"+
    "\2\0\26\20\17\0\1\20\4\0\10\20\1\u0130\15\20"+
    "\2\0\26\20\17\0\1\20\4\0\17\20\1\u0131\6\20"+
    "\2\0\26\20\17\0\1\20\4\0\16\20\1\u0132\7\20"+
    "\2\0\26\20\17\0\1\20\4\0\26\20\2\0\11\20"+
    "\1\u0133\14\20\17\0\1\20\4\0\26\20\2\0\21\20"+
    "\1\u0134\4\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\u0135\11\20\17\0\1\20\4\0\26\20\2\0\1\u0136"+
    "\25\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u0137"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\10\20\1\u0138"+
    "\15\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u0139"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\10\20\1\u013a"+
    "\6\20\1\u013b\1\u013c\5\20\17\0\1\20\4\0\26\20"+
    "\2\0\2\20\1\u013d\23\20\17\0\1\20\4\0\26\20"+
    "\2\0\21\20\1\u013e\4\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\u013f\10\20\17\0\1\20\4\0\26\20"+
    "\2\0\22\20\1\u0140\3\20\17\0\1\20\4\0\26\20"+
    "\2\0\5\20\1\u0141\20\20\17\0\1\20\4\0\26\20"+
    "\2\0\12\20\1\u0142\13\20\17\0\1\20\4\0\26\20"+
    "\2\0\14\20\1\u0143\11\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\u0144\10\20\17\0\1\20\4\0\26\20"+
    "\2\0\15\20\1\u0145\10\20\17\0\1\20\4\0\21\20"+
    "\1\u0146\4\20\2\0\26\20\17\0\1\20\4\0\15\20"+
    "\1\u0147\10\20\2\0\26\20\17\0\1\20\4\0\12\20"+
    "\1\u0148\13\20\2\0\26\20\17\0\1\20\4\0\10\20"+
    "\1\u0149\15\20\2\0\26\20\17\0\1\20\4\0\2\20"+
    "\1\u014a\23\20\2\0\26\20\17\0\1\20\4\0\26\20"+
    "\2\0\14\20\1\u014b\11\20\17\0\1\20\4\0\26\20"+
    "\2\0\11\20\1\u014c\14\20\17\0\1\20\4\0\26\20"+
    "\2\0\1\u014d\25\20\17\0\1\20\4\0\26\20\2\0"+
    "\3\20\1\u014e\22\20\17\0\1\20\4\0\26\20\2\0"+
    "\11\20\1\u014f\14\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\u0150\25\20\17\0\1\20\4\0\26\20\2\0\1\u0151"+
    "\25\20\17\0\1\20\4\0\26\20\2\0\5\20\1\u0152"+
    "\3\20\1\u0153\14\20\17\0\1\20\4\0\26\20\2\0"+
    "\5\20\1\u0154\20\20\17\0\1\20\4\0\26\20\2\0"+
    "\3\20\1\u0155\22\20\17\0\1\20\4\0\26\20\2\0"+
    "\5\20\1\u0156\20\20\17\0\1\20\4\0\26\20\2\0"+
    "\10\20\1\u0157\15\20\17\0\1\20\4\0\26\20\2\0"+
    "\17\20\1\u0158\6\20\17\0\1\20\4\0\26\20\2\0"+
    "\17\20\1\u0159\6\20\17\0\1\20\4\0\26\20\2\0"+
    "\1\u015a\25\20\17\0\1\20\4\0\26\20\2\0\4\20"+
    "\1\u015b\21\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\u015c\11\20\17\0\1\20\4\0\26\20\2\0\13\20"+
    "\1\u015d\12\20\17\0\1\20\4\0\4\20\1\u015e\21\20"+
    "\2\0\26\20\17\0\1\20\4\0\4\20\1\u015f\21\20"+
    "\2\0\26\20\17\0\1\20\4\0\4\20\1\u0160\21\20"+
    "\2\0\26\20\17\0\1\20\4\0\12\20\1\u0161\13\20"+
    "\2\0\26\20\17\0\1\20\4\0\26\20\2\0\21\20"+
    "\1\u0162\4\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\u0163\10\20\17\0\1\20\4\0\26\20\2\0\13\20"+
    "\1\u0164\12\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\u0165\10\20\17\0\1\20\4\0\26\20\2\0\14\20"+
    "\1\u0166\11\20\17\0\1\20\4\0\26\20\2\0\23\20"+
    "\1\u0167\2\20\17\0\1\20\4\0\26\20\2\0\16\20"+
    "\1\u0168\7\20\17\0\1\20\4\0\26\20\2\0\1\20"+
    "\1\u0169\24\20\17\0\1\20\4\0\26\20\2\0\20\20"+
    "\1\u016a\5\20\17\0\1\20\4\0\26\20\2\0\20\20"+
    "\1\u016b\5\20\17\0\1\20\4\0\26\20\2\0\15\20"+
    "\1\u016c\10\20\17\0\1\20\4\0\26\20\2\0\17\20"+
    "\1\u016d\6\20\17\0\1\20\4\0\26\20\2\0\25\20"+
    "\1\u016e\17\0\1\20\4\0\26\20\2\0\3\20\1\u016f"+
    "\22\20\17\0\1\20\4\0\26\20\2\0\4\20\1\u0170"+
    "\21\20\17\0\1\20\4\0\26\20\2\0\20\20\1\u0171"+
    "\5\20\17\0\1\20\4\0\26\20\2\0\22\20\1\u0172"+
    "\3\20\17\0\1\20\4\0\26\20\2\0\2\20\1\u0173"+
    "\23\20\17\0\1\20\4\0\17\20\1\u0174\6\20\2\0"+
    "\26\20\17\0\1\20\4\0\26\20\2\0\14\20\1\u0175"+
    "\11\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u0176"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\22\20\1\u0177"+
    "\3\20\17\0\1\20\4\0\26\20\2\0\21\20\1\u0178"+
    "\4\20\17\0\1\20\4\0\26\20\2\0\11\20\1\u0179"+
    "\14\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u017a"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\12\20\1\u017b"+
    "\13\20\17\0\1\20\4\0\26\20\2\0\21\20\1\u017c"+
    "\4\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u017d"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\17\20\1\u017e"+
    "\6\20\17\0\1\20\4\0\26\20\2\0\5\20\1\u017f"+
    "\20\20\17\0\1\20\4\0\26\20\2\0\5\20\1\u0180"+
    "\20\20\17\0\1\20\4\0\26\20\2\0\20\20\1\u0181"+
    "\5\20\17\0\1\20\4\0\26\20\2\0\15\20\1\u0182"+
    "\10\20\17\0\1\20\4\0\26\20\2\0\1\u0183\25\20"+
    "\17\0\1\20\4\0\26\20\2\0\23\20\1\u0184\2\20"+
    "\17\0\1\20\4\0\26\20\2\0\14\20\1\u0185\11\20"+
    "\17\0\1\20\4\0\26\20\2\0\3\20\1\u0186\22\20"+
    "\17\0\1\20\4\0\26\20\2\0\11\20\1\u0187\14\20"+
    "\17\0\1\20\4\0\26\20\2\0\21\20\1\u0188\4\20"+
    "\17\0\1\20\4\0\26\20\2\0\15\20\1\u0189\10\20"+
    "\17\0\1\20\4\0\26\20\2\0\22\20\1\u018a\3\20"+
    "\17\0\1\20\4\0\26\20\2\0\5\20\1\u018b\20\20"+
    "\17\0\1\20\4\0\26\20\2\0\6\20\1\u018c\17\20"+
    "\17\0\1\20\4\0\26\20\2\0\1\u018d\25\20\17\0"+
    "\1\20\4\0\26\20\2\0\16\20\1\u018e\7\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\u018f\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\21\20\1\u0190\4\20\17\0"+
    "\1\20\4\0\26\20\2\0\21\20\1\u0191\4\20\17\0"+
    "\1\20\4\0\26\20\2\0\14\20\1\u0192\11\20\17\0"+
    "\1\20\4\0\26\20\2\0\10\20\1\u0193\15\20\17\0"+
    "\1\20\4\0\26\20\2\0\17\20\1\u0194\6\20\17\0"+
    "\1\20\4\0\26\20\2\0\17\20\1\u0195\6\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\u0196\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\16\20\1\u0197\7\20\17\0"+
    "\1\20\4\0\26\20\2\0\5\20\1\u0198\20\20\17\0"+
    "\1\20\4\0\26\20\2\0\20\20\1\u0199\5\20\17\0"+
    "\1\20\4\0\26\20\2\0\15\20\1\u019a\10\20\17\0"+
    "\1\20\4\0\26\20\2\0\21\20\1\u019b\4\20\17\0"+
    "\1\20\4\0\26\20\2\0\25\20\1\u019c\17\0\1\20"+
    "\4\0\26\20\2\0\3\20\1\u019d\22\20\17\0\1\20"+
    "\4\0\26\20\2\0\14\20\1\u019e\11\20\17\0\1\20"+
    "\4\0\26\20\2\0\15\20\1\u019f\10\20\17\0\1\20"+
    "\4\0\26\20\2\0\14\20\1\u01a0\11\20\17\0\1\20"+
    "\4\0\26\20\2\0\17\20\1\u01a1\6\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u01a2\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\5\20\1\u01a3\20\20\17\0\1\20"+
    "\4\0\26\20\2\0\20\20\1\u01a4\5\20\17\0\1\20"+
    "\4\0\26\20\2\0\11\20\1\u01a5\14\20\17\0\1\20"+
    "\4\0\26\20\2\0\1\20\1\u01a6\24\20\17\0\1\20"+
    "\4\0\26\20\2\0\25\20\1\u01a7\17\0\1\20\4\0"+
    "\26\20\2\0\5\20\1\u01a8\20\20\17\0\1\20\4\0"+
    "\26\20\2\0\14\20\1\u01a9\11\20\17\0\1\20\4\0"+
    "\26\20\2\0\12\20\1\u01aa\13\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\u01ab\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\21\20\1\u01ac\4\20\17\0\1\20\4\0"+
    "\26\20\2\0\20\20\1\u01ad\5\20\17\0\1\20\4\0"+
    "\26\20\2\0\25\20\1\u01ae\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[24288];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\3\11\2\1\1\11\13\1\2\11"+
    "\20\1\1\11\1\1\3\11\1\0\1\1\1\0\1\1"+
    "\3\11\41\1\1\11\1\0\45\1\1\11\u0131\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[430];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println(
        "Error léxico: carácter no reconocido '"
        + yytext()
        + "' en línea "
        + (yyline + 1)
        + ", columna "
        + (yycolumn + 1)
    );
            }
          // fall through
          case 74: break;
          case 2:
            { 
            }
          // fall through
          case 75: break;
          case 3:
            { return symbol(sym.PAR_A);
            }
          // fall through
          case 76: break;
          case 4:
            { return symbol(sym.PAR_C);
            }
          // fall through
          case 77: break;
          case 5:
            { return symbol(sym.COMA);
            }
          // fall through
          case 78: break;
          case 6:
            { return symbol(sym.ENTERO,Integer.parseInt(yytext()));
            }
          // fall through
          case 79: break;
          case 7:
            { return symbol(sym.DOS_PUNTOS);
            }
          // fall through
          case 80: break;
          case 8:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 81: break;
          case 9:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 82: break;
          case 10:
            { return symbol(sym.ID,yytext());
            }
          // fall through
          case 83: break;
          case 11:
            { return symbol(sym.CORCHETE_A);
            }
          // fall through
          case 84: break;
          case 12:
            { return symbol(sym.CORCHETE_C);
            }
          // fall through
          case 85: break;
          case 13:
            { return symbol(sym.LLAVE_A);
            }
          // fall through
          case 86: break;
          case 14:
            { return symbol(sym.LLAVE_C);
            }
          // fall through
          case 87: break;
          case 15:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 88: break;
          case 16:
            { return symbol(sym.AND);
            }
          // fall through
          case 89: break;
          case 17:
            { System.out.println(
        "Error léxico: identificador inválido '"
        + yytext()
        + "' en línea "
        + (yyline + 1)
        + ", columna "
        + (yycolumn + 1)
    );
            }
          // fall through
          case 90: break;
          case 18:
            { return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 91: break;
          case 19:
            { return symbol(sym.IGUAL_IGUAL);
            }
          // fall through
          case 92: break;
          case 20:
            { return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 93: break;
          case 21:
            { return symbol(sym.IF);
            }
          // fall through
          case 94: break;
          case 22:
            { return symbol(sym.OR);
            }
          // fall through
          case 95: break;
          case 23:
            { return symbol(sym.DECIMAL,Double.parseDouble(yytext()));
            }
          // fall through
          case 96: break;
          case 24:
            { return symbol(sym.RUN);
            }
          // fall through
          case 97: break;
          case 25:
            { return symbol(sym.REST);
            }
          // fall through
          case 98: break;
          case 26:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 99: break;
          case 27:
            { return symbol(sym.MAGE);
            }
          // fall through
          case 100: break;
          case 28:
            { return symbol(sym.MAIN);
            }
          // fall through
          case 101: break;
          case 29:
            { return symbol(sym.SEED);
            }
          // fall through
          case 102: break;
          case 30:
            { return symbol(sym.THEN);
            }
          // fall through
          case 103: break;
          case 31:
            { return symbol(sym.WITH);
            }
          // fall through
          case 104: break;
          case 32:
            { return symbol(sym.SLASH);
            }
          // fall through
          case 105: break;
          case 33:
            { return symbol(sym.MATCH);
            }
          // fall through
          case 106: break;
          case 34:
            { return symbol(sym.RULES);
            }
          // fall through
          case 107: break;
          case 35:
            { return symbol(sym.RANDOM);
            }
          // fall through
          case 108: break;
          case 36:
            { return symbol(sym.ROUNDS);
            }
          // fall through
          case 109: break;
          case 37:
            { return symbol(sym.WAR_CRY);
            }
          // fall through
          case 110: break;
          case 38:
            { return symbol(sym.BONUSES);
            }
          // fall through
          case 111: break;
          case 39:
            { return symbol(sym.INITIAL);
            }
          // fall through
          case 112: break;
          case 40:
            { return symbol(sym.PLAYERS);
            }
          // fall through
          case 113: break;
          case 41:
            { return symbol(sym.SCORING);
            }
          // fall through
          case 114: break;
          case 42:
            { return symbol(sym.WARRIOR);
            }
          // fall through
          case 115: break;
          case 43:
            { return symbol(sym.FIREBALL);
            }
          // fall through
          case 116: break;
          case 44:
            { return symbol(sym.MEDITATE);
            }
          // fall through
          case 117: break;
          case 45:
            { return symbol(sym.GET_MOVE);
            }
          // fall through
          case 118: break;
          case 46:
            { return symbol(sym.LAST_MOVE);
            }
          // fall through
          case 119: break;
          case 47:
            { return symbol(sym.MAGE_COMBO);
            }
          // fall through
          case 120: break;
          case 48:
            { return symbol(sym.SELF_SCORE);
            }
          // fall through
          case 121: break;
          case 49:
            { return symbol(sym.ARCANE_BOLT);
            }
          // fall through
          case 122: break;
          case 50:
            { return symbol(sym.SELF_HEALTH);
            }
          // fall through
          case 123: break;
          case 51:
            { return symbol(sym.HEALING_RUNE);
            }
          // fall through
          case 124: break;
          case 52:
            { return symbol(sym.HEAVY_STRIKE);
            }
          // fall through
          case 125: break;
          case 53:
            { return symbol(sym.SHIELD_BLOCK);
            }
          // fall through
          case 126: break;
          case 54:
            { return symbol(sym.DAMAGE_POINT);
            }
          // fall through
          case 127: break;
          case 55:
            { return symbol(sym.ROUND_NUMBER);
            }
          // fall through
          case 128: break;
          case 56:
            { return symbol(sym.SELF_HISTORY);
            }
          // fall through
          case 129: break;
          case 57:
            { return symbol(sym.TOTAL_ROUNDS);
            }
          // fall through
          case 130: break;
          case 58:
            { return symbol(sym.MAGIC_BARRIER);
            }
          // fall through
          case 131: break;
          case 59:
            { return symbol(sym.HEALING_POINT);
            }
          // fall through
          case 132: break;
          case 60:
            { return symbol(sym.SELF_RESOURCE);
            }
          // fall through
          case 133: break;
          case 61:
            { return symbol(sym.VICTORY_BONUS);
            }
          // fall through
          case 134: break;
          case 62:
            { return symbol(sym.WARRIOR_COMBO);
            }
          // fall through
          case 135: break;
          case 63:
            { return symbol(sym.OPPONENT_SCORE);
            }
          // fall through
          case 136: break;
          case 64:
            { return symbol(sym.GET_MOVES_COUNT);
            }
          // fall through
          case 137: break;
          case 65:
            { return symbol(sym.OPPONENT_HEALTH);
            }
          // fall through
          case 138: break;
          case 66:
            { return symbol(sym.GET_LAST_N_MOVES);
            }
          // fall through
          case 139: break;
          case 67:
            { return symbol(sym.OPPONENT_HISTORY);
            }
          // fall through
          case 140: break;
          case 68:
            { return symbol(sym.MAGE_COMBO_POINTS);
            }
          // fall through
          case 141: break;
          case 69:
            { return symbol(sym.OPPONENT_RESOURCE);
            }
          // fall through
          case 142: break;
          case 70:
            { return symbol(sym.LOW_HEALTH_VICTORY);
            }
          // fall through
          case 143: break;
          case 71:
            { return symbol(sym.SUCCESSFUL_DEFENSE);
            }
          // fall through
          case 144: break;
          case 72:
            { return symbol(sym.WARRIOR_COMBO_POINTS);
            }
          // fall through
          case 145: break;
          case 73:
            { return symbol(sym.FAILED_ACTION_PENALTY);
            }
          // fall through
          case 146: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
