package analizadores;
import modelo.Estrategia;
import java.util.LinkedList;
import modelo.Regla;
import modelo.Condicion;
import modelo.CuerpoEstrategia;
import modelo.Partida;
import modelo.Scoring;
import modelo.Bonuses;
import modelo.CuerpoPartida;
import modelo.Principal;

/* =========================================
                 TERMINALES
   ========================================= */

/* PALABRAS RESERVADAS */
terminal MAGE;
terminal WARRIOR;
terminal INITIAL;
terminal RULES;
terminal IF;
terminal THEN;
terminal ELSE;

/* PARTIDAS */
terminal MATCH;
terminal PLAYERS;
terminal ROUNDS;
terminal SCORING;
terminal BONUSES;

/* PUNTO DE ENTRADA */
terminal MAIN;
terminal RUN;
terminal WITH;
terminal SEED;

/* SCORING */
terminal DAMAGE_POINT;
terminal HEALING_POINT;
terminal SUCCESSFUL_DEFENSE;
terminal VICTORY_BONUS;
terminal FAILED_ACTION_PENALTY;

/* BONUSES */
terminal MAGE_COMBO;
terminal MAGE_COMBO_POINTS;
terminal WARRIOR_COMBO;
terminal WARRIOR_COMBO_POINTS;
terminal LOW_HEALTH_VICTORY;

/* FUNCIONES DEL SISTEMA */
terminal GET_MOVE;
terminal LAST_MOVE;
terminal GET_MOVES_COUNT;
terminal GET_LAST_N_MOVES;

/* ESTADOS DEL SISTEMA */
terminal ROUND_NUMBER;
terminal TOTAL_ROUNDS;
terminal SELF_HEALTH;
terminal OPPONENT_HEALTH;
terminal SELF_RESOURCE;
terminal OPPONENT_RESOURCE;
terminal SELF_SCORE;
terminal OPPONENT_SCORE;
terminal SELF_HISTORY;
terminal OPPONENT_HISTORY;

terminal RANDOM;

/* ACCIONES */
terminal ARCANE_BOLT;
terminal FIREBALL;
terminal MAGIC_BARRIER;
terminal HEALING_RUNE;
terminal MEDITATE;
terminal SLASH;
terminal HEAVY_STRIKE;
terminal SHIELD_BLOCK;
terminal WAR_CRY;
terminal REST;

/* OPERADORES DE COMPARACION */
terminal IGUAL_IGUAL;
terminal DIFERENTE;
terminal MAYOR_IGUAL;
terminal MENOR_IGUAL;
terminal MAYOR;
terminal MENOR;

/* OPERADORES ARITMETICOS */

terminal MENOS;

/* OPERADORES BOOLEANOS */
terminal AND;
terminal OR;
terminal NOT;

/* SIMBOLOS */
terminal LLAVE_A;
terminal LLAVE_C;
terminal CORCHETE_A;
terminal CORCHETE_C;
terminal PAR_A;
terminal PAR_C;
terminal DOS_PUNTOS;
terminal COMA;

/* VALORES */
terminal Double DECIMAL;
terminal Integer ENTERO;
terminal String ID;

/* =========================================
                 NO TERMINALES
   ========================================= */

non terminal inicio;

non terminal LinkedList<Estrategia> lista_estrategias;
non terminal Estrategia estrategia;
non terminal Estrategia estrategia_mago;
non terminal Estrategia estrategia_guerrero;
non terminal CuerpoEstrategia cuerpo_mago;
non terminal CuerpoEstrategia cuerpo_guerrero;
non terminal String accion;
non terminal String accion_mago;
non terminal String accion_guerrero;
non terminal LinkedList<Regla> lista_reglas_mago;
non terminal LinkedList<Regla> lista_reglas_guerrero;
non terminal Regla regla_mago;
non terminal Regla regla_guerrero;
non terminal Regla regla_else_mago;
non terminal Regla regla_else_guerrero;
non terminal Condicion condicion;
non terminal Condicion condicion_and;
non terminal Condicion condicion_not;
non terminal Condicion condicion_base;
non terminal Condicion comparacion;
non terminal Object valor_numerico;
non terminal Object expresion_numerica;
non terminal String estado_entero;
non terminal String operador_comparacion;
non terminal funcion_accion;
non terminal funcion_lista;
non terminal historial;
non terminal fuente_historial;
non terminal funcion_entera;
non terminal valor_accion;
non terminal lista_acciones;
non terminal elementos_acciones;
non terminal valor_lista;
non terminal LinkedList<Partida> lista_partidas;
non terminal Partida partida;
non terminal CuerpoPartida cuerpo_partida;
non terminal LinkedList<String> jugadores;
non terminal Integer rondas;
non terminal Scoring scoring;
non terminal Scoring lista_scoring;
non terminal Bonuses bonuses;
non terminal Bonuses lista_bonuses;
non terminal LinkedList<String> lista_acciones_mago;
non terminal LinkedList<String> elementos_acciones_mago;
non terminal LinkedList<String> lista_acciones_guerrero;
non terminal LinkedList<String> elementos_acciones_guerrero;
non terminal Principal cuerpo_principal;
non terminal Principal principal;
non terminal Principal instruccion_run;
non terminal LinkedList<String> lista_partidas_run;

start with inicio;

inicio ::=
      lista_estrategias: estrategias
      lista_partidas: partidas
      principal: main
      {:
          System.out.println("===== ESTRATEGIAS CARGADAS =====");

          for (Estrategia e : estrategias) {
              System.out.println(e);
          }
          System.out.println("===== PARTIDAS CARGADAS =====");

          for (Partida p : partidas) {
              System.out.println(p);
          }
           System.out.println("===== MAIN =====");
          System.out.println(main);
      :}
;
/* ----------------------------------------ESTRATEGIAS */
lista_estrategias ::=
      lista_estrategias: lista  estrategia: e
        {:
          lista.add(e);
          RESULT = lista;
        :}
    | estrategia: e
        {:
          LinkedList<Estrategia> lista = new LinkedList<Estrategia>();
          lista.add(e);
          RESULT = lista;
        :}
;

estrategia ::=
      estrategia_mago: e        {: RESULT = e; :}
    | estrategia_guerrero: e    {: RESULT = e; :}
;

estrategia_mago ::=
      MAGE ID: id  LLAVE_A cuerpo_mago: cuerpo LLAVE_C
            {:
          RESULT = new Estrategia(
              id,
              "mage",
              cuerpo.getAccionInicial(),
              cuerpo.getReglas()
          );
      :}
;

estrategia_guerrero ::=
      WARRIOR ID: id LLAVE_A cuerpo_guerrero: cuerpo LLAVE_C
       {:
          RESULT = new Estrategia(
              id,
              "warrior",
              cuerpo.getAccionInicial(),
              cuerpo.getReglas()
          );
      :}
;

cuerpo_mago ::=
      INITIAL DOS_PUNTOS accion_mago : accionInicial
      RULES DOS_PUNTOS CORCHETE_A
      lista_reglas_mago: reglas
      regla_else_mago: reglaElse
      CORCHETE_C
       {:
          reglas.add(reglaElse);
          RESULT = new CuerpoEstrategia(accionInicial, reglas);
      :}
;

cuerpo_guerrero ::=
      INITIAL DOS_PUNTOS accion_guerrero : accionInicial 
      RULES DOS_PUNTOS CORCHETE_A
      lista_reglas_guerrero: reglas
      regla_else_guerrero: reglaElse
      CORCHETE_C
       {:
          reglas.add(reglaElse);
          RESULT = new CuerpoEstrategia(accionInicial, reglas);
      :}
;

accion ::=
      accion_mago : a       {: RESULT = a; :}
    | accion_guerrero : a   {: RESULT = a; :}
;

accion_mago ::=
       ARCANE_BOLT  {: RESULT = "ARCANE_BOLT"; :}
    | FIREBALL      {: RESULT = "FIREBALL"; :}
    | MAGIC_BARRIER {: RESULT = "MAGIC_BARRIER"; :}
    | HEALING_RUNE  {: RESULT = "HEALING_RUNE"; :}
    | MEDITATE      {: RESULT = "MEDITATE"; :}
;

accion_guerrero ::=
       SLASH        {: RESULT = "SLASH"; :}
    | HEAVY_STRIKE  {: RESULT = "HEAVY_STRIKE"; :}
    | SHIELD_BLOCK  {: RESULT = "SHIELD_BLOCK"; :}
    | WAR_CRY       {: RESULT = "WAR_CRY"; :}
    | REST          {: RESULT = "REST"; :}
;

regla_mago ::=
      IF condicion: c THEN accion_mago: a COMA
      {:
          RESULT = new Regla(c, a, false);
      :}
      
;

regla_guerrero ::=
      IF condicion: c THEN accion_guerrero: a COMA
       {:
          RESULT = new Regla(c, a, false);
      :}
      
;

regla_else_mago ::=
      ELSE accion_mago: a
      {:
          RESULT = new Regla(null, a, true);
      :}
      
;

regla_else_guerrero ::=
      ELSE accion_guerrero: a
       {:
          RESULT = new Regla(null, a, true);
      :}
;

lista_reglas_mago ::=
      lista_reglas_mago: lista regla_mago: r
      {:
          lista.add(r);
          RESULT = lista;
      :}
    | regla_mago: r
      {:
          LinkedList<Regla> lista = new LinkedList<Regla>();
          lista.add(r);
          RESULT = lista;
      :}
;

lista_reglas_guerrero ::=
      lista_reglas_guerrero: lista regla_guerrero: r
      {:
          lista.add(r);
          RESULT = lista;
      :}
    | regla_guerrero: r
      {:
          LinkedList<Regla> lista = new LinkedList<Regla>();
          lista.add(r);
          RESULT = lista;
      :}
;

condicion ::=
      condicion: c1 OR condicion_and: c2
      {:
          RESULT = new Condicion(c1, "OR", c2);
      :}
    | condicion_and: c
      {:
          RESULT = c;
      :}  
;

condicion_and ::=
      condicion_and: c1 AND condicion_not: c2
       {:
          RESULT = new Condicion(c1, "AND", c2);
       :}
    | condicion_not: c
      {:
          RESULT = c;
      :}
;

condicion_not ::=
      NOT condicion_not: c
      {:
          RESULT = new Condicion(c, "NOT", null);
      :}
    | condicion_base: c
       {:
          RESULT = c;
      :}
;

condicion_base ::=
      comparacion: c
      {:
          RESULT = c;
      :}
    | PAR_A condicion: c PAR_C
      {:
          RESULT = c;
      :}
;

operador_comparacion ::=
      IGUAL_IGUAL   {: RESULT = "=="; :}
    | DIFERENTE     {: RESULT = "!="; :}
    | MAYOR         {: RESULT = ">"; :}
    | MENOR         {: RESULT = "<"; :}
    | MAYOR_IGUAL   {: RESULT = ">="; :}
    | MENOR_IGUAL   {: RESULT = "<="; :}
;

estado_entero ::=
      ROUND_NUMBER          {: RESULT = "ROUND_NUMBER"; :}
    | TOTAL_ROUNDS          {: RESULT = "TOTAL_ROUNDS"; :}
    | SELF_HEALTH           {: RESULT = "SELF_HEALTH"; :}
    | OPPONENT_HEALTH       {: RESULT = "OPPONENT_HEALTH"; :}
    | SELF_RESOURCE         {: RESULT = "SELF_RESOURCE"; :}
    | OPPONENT_RESOURCE     {: RESULT = "OPPONENT_RESOURCE"; :}
    | SELF_SCORE            {: RESULT = "SELF_SCORE"; :}
    | OPPONENT_SCORE        {: RESULT = "OPPONENT_SCORE"; :}
;

valor_numerico ::=
      estado_entero: e      {: RESULT = e; :}  
    | ENTERO: e             {: RESULT = e; :}
    | RANDOM                {: RESULT = "RANDOM"; :}
    | DECIMAL: d            {: RESULT = d; :}
    | funcion_entera: f     {: RESULT = f; :}
;

comparacion ::=
      expresion_numerica: izq operador_comparacion: op expresion_numerica: der
      {:
          RESULT = new Condicion(izq, op, der);
      :}
    | valor_accion: izq IGUAL_IGUAL valor_accion: der
      {:
          RESULT = new Condicion(izq, "==", der);
      :}

    | valor_accion: izq DIFERENTE valor_accion: der
      {:
          RESULT = new Condicion(izq, "!=", der);
      :}

    | valor_lista: izq IGUAL_IGUAL valor_lista: der
      {:
          RESULT = new Condicion(izq, "==", der);
      :}

    | valor_lista: izq DIFERENTE valor_lista: der
      {:
          RESULT = new Condicion(izq, "!=", der);
      :}
;

expresion_numerica ::=
      expresion_numerica: e1 MENOS valor_numerico: e2
      {:
          RESULT = "(" + e1 + " - " + e2 + ")";
      :}
    | valor_numerico: v
      {:
          RESULT = v;
      :}
;
historial ::=
      SELF_HISTORY
    | OPPONENT_HISTORY
;

funcion_accion ::=
      GET_MOVE PAR_A historial COMA ENTERO PAR_C
    |
      LAST_MOVE PAR_A historial PAR_C
;

funcion_lista ::=
      GET_LAST_N_MOVES
      PAR_A
      historial
      COMA
      ENTERO
      PAR_C
;

fuente_historial ::=
      historial
    | funcion_lista
;

funcion_entera ::=
      GET_MOVES_COUNT
      PAR_A
      fuente_historial
      COMA
      accion
      PAR_C
;

valor_accion ::=
      accion
    | funcion_accion
;

lista_acciones ::=
      CORCHETE_A elementos_acciones CORCHETE_C
;

elementos_acciones ::=
      elementos_acciones COMA accion
    | accion
;

valor_lista ::=
      lista_acciones
    | funcion_lista
;



/* ----------------------------------------PARTIDAS */
partida ::=
      MATCH ID: id LLAVE_A
      cuerpo_partida: cuerpo
      LLAVE_C
      {:
          RESULT = new Partida(
              id,
              cuerpo.getJugadores().get(0),
              cuerpo.getJugadores().get(1),
              cuerpo.getRondas(),
              cuerpo.getScoring(),
              cuerpo.getBonuses()
          );
      :}
;

cuerpo_partida ::=
      jugadores: j
      rondas: r
      scoring: s
      bonuses: b
       {:
          RESULT = new CuerpoPartida(
              j,
              r,
              s,
              b
          );
      :}
;

lista_partidas ::=
      lista_partidas: lista partida: p
       {:
          lista.add(p);
          RESULT = lista;
      :}
    | partida: p
        {:
          LinkedList<Partida> lista = new LinkedList<Partida>();
          lista.add(p);
          RESULT = lista;
      :}
;

jugadores ::=
      PLAYERS DOS_PUNTOS
      CORCHETE_A
      ID: j1 COMA ID: j2
      CORCHETE_C
      {:
          LinkedList<String> jugadores = new LinkedList<String>();
          jugadores.add(j1);
          jugadores.add(j2);

          RESULT = jugadores;
      :}
;

rondas ::=
      ROUNDS DOS_PUNTOS ENTERO: r
      {:
          RESULT = r;
      :}
;

scoring ::=
      SCORING DOS_PUNTOS
      LLAVE_A
      lista_scoring: s
      LLAVE_C
      {:
          RESULT = s;
      :}
;

bonuses ::=
      BONUSES DOS_PUNTOS
      LLAVE_A
      lista_bonuses:b
      LLAVE_C
      {:
          RESULT = b;
      :}
;

lista_scoring ::=
      DAMAGE_POINT DOS_PUNTOS ENTERO: damage COMA
      HEALING_POINT DOS_PUNTOS ENTERO: healing COMA
      SUCCESSFUL_DEFENSE DOS_PUNTOS ENTERO: defense COMA
      VICTORY_BONUS DOS_PUNTOS ENTERO: victory COMA
      FAILED_ACTION_PENALTY DOS_PUNTOS ENTERO: penalty
      {:
          RESULT = new Scoring(
              damage,
              healing,
              defense,
              victory,
              penalty
          );
      :}
;

lista_bonuses ::=
      MAGE_COMBO DOS_PUNTOS lista_acciones_mago: mageCombo COMA
      MAGE_COMBO_POINTS DOS_PUNTOS ENTERO: magePoints COMA
      WARRIOR_COMBO DOS_PUNTOS lista_acciones_guerrero: warriorCombo COMA
      WARRIOR_COMBO_POINTS DOS_PUNTOS ENTERO: warriorPoints COMA
      LOW_HEALTH_VICTORY DOS_PUNTOS ENTERO: lowHealth
      {:
          RESULT = new Bonuses(
              mageCombo,
              magePoints,
              warriorCombo,
              warriorPoints,
              lowHealth
          );
      :}
;

lista_acciones_mago ::=
      CORCHETE_A elementos_acciones_mago: lista CORCHETE_C
      {:
          RESULT = lista;
      :}
;

elementos_acciones_mago ::=
      elementos_acciones_mago: lista COMA accion_mago: a
      {:
          lista.add(a);
          RESULT = lista;
      :}
    | accion_mago: a
      {:
          LinkedList<String> lista = new LinkedList<String>();
          lista.add(a);
          RESULT = lista;
      :}
;

lista_acciones_guerrero ::=
      CORCHETE_A elementos_acciones_guerrero: lista CORCHETE_C
      {:
          RESULT = lista;
      :}
;

elementos_acciones_guerrero ::=
      elementos_acciones_guerrero: lista COMA accion_guerrero: a
       {:
          lista.add(a);
          RESULT = lista;
       :}
    | accion_guerrero: a
       {:
          LinkedList<String> lista = new LinkedList<String>();
          lista.add(a);
          RESULT = lista;
      :}
;
/* ----------------------------------------MAIN */
principal ::=
      MAIN LLAVE_A
      cuerpo_principal:p
      LLAVE_C
      {:
          RESULT = p;
      :}
;

cuerpo_principal ::=
     instruccion_run:p
      {:
          RESULT = p;
      :}
;

instruccion_run ::=
      RUN
      CORCHETE_A
      lista_partidas_run: partidas
      CORCHETE_C
      WITH
      LLAVE_A
      SEED DOS_PUNTOS ENTERO: seed
      LLAVE_C
       {:
          RESULT = new Principal(partidas, seed);
      :}
;

lista_partidas_run ::=
      lista_partidas_run: lista COMA ID: id
       {:
          lista.add(id);
          RESULT = lista;
      :}
    | ID: id
      {:
          LinkedList<String> lista = new LinkedList<String>();
          lista.add(id);
          RESULT = lista;
      :}
;
