
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\145\000\002\002\004\000\002\002\005\000\002\003" +
    "\004\000\002\003\003\000\002\022\004\000\002\022\003" +
    "\000\002\004\003\000\002\004\003\000\002\006\007\000" +
    "\002\007\007\000\002\010\013\000\002\011\013\000\002" +
    "\005\003\000\002\005\003\000\002\012\003\000\002\012" +
    "\003\000\002\012\003\000\002\012\003\000\002\012\003" +
    "\000\002\013\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\013\003\000\002\016\007\000\002" +
    "\017\007\000\002\020\004\000\002\021\004\000\002\014" +
    "\004\000\002\014\003\000\002\015\004\000\002\015\003" +
    "\000\002\023\005\000\002\023\003\000\002\024\005\000" +
    "\002\024\003\000\002\025\004\000\002\025\003\000\002" +
    "\026\003\000\002\026\005\000\002\032\003\000\002\032" +
    "\003\000\002\032\003\000\002\032\003\000\002\032\003" +
    "\000\002\032\003\000\002\031\003\000\002\031\003\000" +
    "\002\031\003\000\002\031\003\000\002\031\003\000\002" +
    "\031\003\000\002\031\003\000\002\031\003\000\002\030" +
    "\003\000\002\030\003\000\002\030\003\000\002\030\003" +
    "\000\002\030\003\000\002\027\005\000\002\027\005\000" +
    "\002\027\005\000\002\027\005\000\002\027\005\000\002" +
    "\035\003\000\002\035\003\000\002\033\010\000\002\033" +
    "\006\000\002\034\010\000\002\036\003\000\002\036\003" +
    "\000\002\037\010\000\002\040\003\000\002\040\003\000" +
    "\002\041\005\000\002\042\005\000\002\042\003\000\002" +
    "\043\003\000\002\043\003\000\002\044\005\000\002\044" +
    "\003\000\002\045\007\000\002\046\006\000\002\047\011" +
    "\000\002\050\005\000\002\051\007\000\002\053\007\000" +
    "\002\052\025\000\002\054\025\000\002\055\005\000\002" +
    "\056\005\000\002\056\003\000\002\057\005\000\002\060" +
    "\005\000\002\060\003\000\002\061\006\000\002\062\004" +
    "\000\002\062\003\000\002\063\014\000\002\064\005\000" +
    "\002\064\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\374\000\006\004\012\005\004\001\002\000\004\113" +
    "\351\001\002\000\010\004\ufffe\005\ufffe\013\ufffe\001\002" +
    "\000\010\004\ufffb\005\ufffb\013\ufffb\001\002\000\010\004" +
    "\ufffa\005\ufffa\013\ufffa\001\002\000\010\004\012\005\004" +
    "\013\202\001\002\000\004\002\201\001\002\000\004\113" +
    "\013\001\002\000\004\101\014\001\002\000\004\006\015" +
    "\001\002\000\004\107\020\001\002\000\004\102\017\001" +
    "\002\000\010\004\ufff9\005\ufff9\013\ufff9\001\002\000\014" +
    "\055\023\056\025\057\026\060\024\061\021\001\002\000" +
    "\024\007\uffef\011\uffef\067\uffef\070\uffef\076\uffef\077\uffef" +
    "\104\uffef\106\uffef\110\uffef\001\002\000\004\007\027\001" +
    "\002\000\024\007\ufff3\011\ufff3\067\ufff3\070\ufff3\076\ufff3" +
    "\077\ufff3\104\ufff3\106\ufff3\110\ufff3\001\002\000\024\007" +
    "\ufff0\011\ufff0\067\ufff0\070\ufff0\076\ufff0\077\ufff0\104\ufff0" +
    "\106\ufff0\110\ufff0\001\002\000\024\007\ufff2\011\ufff2\067" +
    "\ufff2\070\ufff2\076\ufff2\077\ufff2\104\ufff2\106\ufff2\110\ufff2" +
    "\001\002\000\024\007\ufff1\011\ufff1\067\ufff1\070\ufff1\076" +
    "\ufff1\077\ufff1\104\ufff1\106\ufff1\110\ufff1\001\002\000\004" +
    "\107\030\001\002\000\004\103\031\001\002\000\004\010" +
    "\034\001\002\000\006\010\034\012\176\001\002\000\006" +
    "\010\uffe4\012\uffe4\001\002\000\072\036\100\037\073\040" +
    "\036\041\055\042\072\043\064\044\070\045\075\046\050" +
    "\047\047\050\104\051\057\054\040\055\023\056\025\057" +
    "\026\060\024\061\021\062\045\063\041\064\051\065\101" +
    "\066\074\100\054\103\053\105\065\111\061\112\046\001" +
    "\002\000\006\067\170\070\171\001\002\000\004\105\161" +
    "\001\002\000\016\011\uffb9\067\uffb9\070\uffb9\076\uffb9\077" +
    "\uffb9\106\uffb9\001\002\000\030\011\uffc9\067\uffc9\070\uffc9" +
    "\071\uffc9\072\uffc9\073\uffc9\074\uffc9\075\uffc9\076\uffc9\077" +
    "\uffc9\106\uffc9\001\002\000\024\007\uffed\011\uffed\067\uffed" +
    "\070\uffed\076\uffed\077\uffed\104\uffed\106\uffed\110\uffed\001" +
    "\002\000\012\011\uffdb\076\uffdb\077\uffdb\106\uffdb\001\002" +
    "\000\022\011\ufff5\067\ufff5\070\ufff5\076\ufff5\077\ufff5\104" +
    "\ufff5\106\ufff5\110\ufff5\001\002\000\006\011\156\077\141" +
    "\001\002\000\024\007\uffee\011\uffee\067\uffee\070\uffee\076" +
    "\uffee\077\uffee\104\uffee\106\uffee\110\uffee\001\002\000\030" +
    "\011\uffca\067\uffca\070\uffca\071\uffca\072\uffca\073\uffca\074" +
    "\uffca\075\uffca\076\uffca\077\uffca\106\uffca\001\002\000\030" +
    "\011\uffce\067\uffce\070\uffce\071\uffce\072\uffce\073\uffce\074" +
    "\uffce\075\uffce\076\uffce\077\uffce\106\uffce\001\002\000\030" +
    "\011\uffcf\067\uffcf\070\uffcf\071\uffcf\072\uffcf\073\uffcf\074" +
    "\uffcf\075\uffcf\076\uffcf\077\uffcf\106\uffcf\001\002\000\024" +
    "\007\uffec\011\uffec\067\uffec\070\uffec\076\uffec\077\uffec\104" +
    "\uffec\106\uffec\110\uffec\001\002\000\016\011\uffb3\067\uffb3" +
    "\070\uffb3\076\uffb3\077\uffb3\106\uffb3\001\002\000\026\055" +
    "\023\056\025\057\026\060\024\061\021\062\045\063\041" +
    "\064\051\065\101\066\074\001\002\000\072\036\100\037" +
    "\073\040\036\041\055\042\072\043\064\044\070\045\075" +
    "\046\050\047\047\050\104\051\057\054\040\055\023\056" +
    "\025\057\026\060\024\061\021\062\045\063\041\064\051" +
    "\065\101\066\074\100\054\103\053\105\065\111\061\112" +
    "\046\001\002\000\004\105\143\001\002\000\022\011\ufff4" +
    "\067\ufff4\070\ufff4\076\ufff4\077\ufff4\104\ufff4\106\ufff4\110" +
    "\ufff4\001\002\000\030\011\uffcc\067\uffcc\070\uffcc\071\uffcc" +
    "\072\uffcc\073\uffcc\074\uffcc\075\uffcc\076\uffcc\077\uffcc\106" +
    "\uffcc\001\002\000\016\011\uffb4\067\uffb4\070\uffb4\076\uffb4" +
    "\077\uffb4\106\uffb4\001\002\000\030\011\uffc8\067\uffc8\070" +
    "\uffc8\071\uffc8\072\uffc8\073\uffc8\074\uffc8\075\uffc8\076\uffc8" +
    "\077\uffc8\106\uffc8\001\002\000\030\011\uffb1\067\uffb1\070" +
    "\uffb1\071\uffb1\072\uffb1\073\uffb1\074\uffb1\075\uffb1\076\uffb1" +
    "\077\uffb1\106\uffb1\001\002\000\030\011\uffc7\067\uffc7\070" +
    "\uffc7\071\uffc7\072\uffc7\073\uffc7\074\uffc7\075\uffc7\076\uffc7" +
    "\077\uffc7\106\uffc7\001\002\000\030\011\uffd2\067\uffd2\070" +
    "\uffd2\071\uffd2\072\uffd2\073\uffd2\074\uffd2\075\uffd2\076\uffd2" +
    "\077\uffd2\106\uffd2\001\002\000\072\036\100\037\073\040" +
    "\036\041\055\042\072\043\064\044\070\045\075\046\050" +
    "\047\047\050\104\051\057\054\040\055\023\056\025\057" +
    "\026\060\024\061\021\062\045\063\041\064\051\065\101" +
    "\066\074\100\054\103\053\105\065\111\061\112\046\001" +
    "\002\000\012\011\uffdc\076\uffdc\077\uffdc\106\uffdc\001\002" +
    "\000\030\011\uffcb\067\uffcb\070\uffcb\071\uffcb\072\uffcb\073" +
    "\uffcb\074\uffcb\075\uffcb\076\uffcb\077\uffcb\106\uffcb\001\002" +
    "\000\030\011\uffd1\067\uffd1\070\uffd1\071\uffd1\072\uffd1\073" +
    "\uffd1\074\uffd1\075\uffd1\076\uffd1\077\uffd1\106\uffd1\001\002" +
    "\000\020\067\125\070\126\071\134\072\132\073\131\074" +
    "\130\075\127\001\002\000\030\011\uffd3\067\uffd3\070\uffd3" +
    "\071\uffd3\072\uffd3\073\uffd3\074\uffd3\075\uffd3\076\uffd3\077" +
    "\uffd3\106\uffd3\001\002\000\004\105\122\001\002\000\024" +
    "\007\uffea\011\uffea\067\uffea\070\uffea\076\uffea\077\uffea\104" +
    "\uffea\106\uffea\110\uffea\001\002\000\030\011\uffd0\067\uffd0" +
    "\070\uffd0\071\uffd0\072\uffd0\073\uffd0\074\uffd0\075\uffd0\076" +
    "\uffd0\077\uffd0\106\uffd0\001\002\000\012\011\uffde\076\uffde" +
    "\077\uffde\106\uffde\001\002\000\012\011\uffe0\076\120\077" +
    "\uffe0\106\uffe0\001\002\000\004\105\111\001\002\000\024" +
    "\007\uffeb\011\uffeb\067\uffeb\070\uffeb\076\uffeb\077\uffeb\104" +
    "\uffeb\106\uffeb\110\uffeb\001\002\000\006\067\105\070\106" +
    "\001\002\000\016\011\uffb8\067\uffb8\070\uffb8\076\uffb8\077" +
    "\uffb8\106\uffb8\001\002\000\030\011\uffcd\067\uffcd\070\uffcd" +
    "\071\uffcd\072\uffcd\073\uffcd\074\uffcd\075\uffcd\076\uffcd\077" +
    "\uffcd\106\uffcd\001\002\000\032\036\100\037\073\055\023" +
    "\056\025\057\026\060\024\061\021\062\045\063\041\064" +
    "\051\065\101\066\074\001\002\000\032\036\100\037\073" +
    "\055\023\056\025\057\026\060\024\061\021\062\045\063" +
    "\041\064\051\065\101\066\074\001\002\000\012\011\uffc4" +
    "\076\uffc4\077\uffc4\106\uffc4\001\002\000\012\011\uffc5\076" +
    "\uffc5\077\uffc5\106\uffc5\001\002\000\006\052\113\053\114" +
    "\001\002\000\004\110\115\001\002\000\006\106\uffc1\110" +
    "\uffc1\001\002\000\006\106\uffc0\110\uffc0\001\002\000\004" +
    "\112\116\001\002\000\004\106\117\001\002\000\016\011" +
    "\uffbf\067\uffbf\070\uffbf\076\uffbf\077\uffbf\106\uffbf\001\002" +
    "\000\072\036\100\037\073\040\036\041\055\042\072\043" +
    "\064\044\070\045\075\046\050\047\047\050\104\051\057" +
    "\054\040\055\023\056\025\057\026\060\024\061\021\062" +
    "\045\063\041\064\051\065\101\066\074\100\054\103\053" +
    "\105\065\111\061\112\046\001\002\000\012\011\uffdf\076" +
    "\uffdf\077\uffdf\106\uffdf\001\002\000\006\052\113\053\114" +
    "\001\002\000\004\106\124\001\002\000\016\011\uffbe\067" +
    "\uffbe\070\uffbe\076\uffbe\077\uffbe\106\uffbe\001\002\000\032" +
    "\040\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\046\uffd9\047" +
    "\uffd9\050\uffd9\051\uffd9\054\uffd9\111\uffd9\112\uffd9\001\002" +
    "\000\032\040\uffd8\042\uffd8\043\uffd8\044\uffd8\045\uffd8\046" +
    "\uffd8\047\uffd8\050\uffd8\051\uffd8\054\uffd8\111\uffd8\112\uffd8" +
    "\001\002\000\032\040\036\042\072\043\064\044\070\045" +
    "\075\046\050\047\047\050\104\051\057\054\040\111\061" +
    "\112\046\001\002\000\032\040\uffd6\042\uffd6\043\uffd6\044" +
    "\uffd6\045\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6\054\uffd6" +
    "\111\uffd6\112\uffd6\001\002\000\032\040\uffd7\042\uffd7\043" +
    "\uffd7\044\uffd7\045\uffd7\046\uffd7\047\uffd7\050\uffd7\051\uffd7" +
    "\054\uffd7\111\uffd7\112\uffd7\001\002\000\032\040\uffd4\042" +
    "\uffd4\043\uffd4\044\uffd4\045\uffd4\046\uffd4\047\uffd4\050\uffd4" +
    "\051\uffd4\054\uffd4\111\uffd4\112\uffd4\001\002\000\032\040" +
    "\036\042\072\043\064\044\070\045\075\046\050\047\047" +
    "\050\104\051\057\054\040\111\061\112\046\001\002\000" +
    "\032\040\uffd5\042\uffd5\043\uffd5\044\uffd5\045\uffd5\046\uffd5" +
    "\047\uffd5\050\uffd5\051\uffd5\054\uffd5\111\uffd5\112\uffd5\001" +
    "\002\000\014\011\uffc6\075\127\076\uffc6\077\uffc6\106\uffc6" +
    "\001\002\000\030\011\uffb2\067\uffb2\070\uffb2\071\uffb2\072" +
    "\uffb2\073\uffb2\074\uffb2\075\uffb2\076\uffb2\077\uffb2\106\uffb2" +
    "\001\002\000\006\077\141\106\140\001\002\000\012\011" +
    "\uffda\076\uffda\077\uffda\106\uffda\001\002\000\072\036\100" +
    "\037\073\040\036\041\055\042\072\043\064\044\070\045" +
    "\075\046\050\047\047\050\104\051\057\054\040\055\023" +
    "\056\025\057\026\060\024\061\021\062\045\063\041\064" +
    "\051\065\101\066\074\100\054\103\053\105\065\111\061" +
    "\112\046\001\002\000\012\011\uffe1\076\120\077\uffe1\106" +
    "\uffe1\001\002\000\006\052\113\053\114\001\002\000\004" +
    "\110\145\001\002\000\004\112\146\001\002\000\004\106" +
    "\147\001\002\000\020\011\uffbd\067\uffbd\070\uffbd\076\uffbd" +
    "\077\uffbd\106\uffbd\110\uffbd\001\002\000\012\011\uffdd\076" +
    "\uffdd\077\uffdd\106\uffdd\001\002\000\006\104\154\110\153" +
    "\001\002\000\006\104\uffb5\110\uffb5\001\002\000\026\055" +
    "\023\056\025\057\026\060\024\061\021\062\045\063\041" +
    "\064\051\065\101\066\074\001\002\000\016\011\uffb7\067" +
    "\uffb7\070\uffb7\076\uffb7\077\uffb7\106\uffb7\001\002\000\006" +
    "\104\uffb6\110\uffb6\001\002\000\014\055\023\056\025\057" +
    "\026\060\024\061\021\001\002\000\004\110\160\001\002" +
    "\000\006\010\uffe9\012\uffe9\001\002\000\010\041\055\052" +
    "\113\053\114\001\002\000\004\110\uffbc\001\002\000\004" +
    "\110\165\001\002\000\004\110\uffbb\001\002\000\026\055" +
    "\023\056\025\057\026\060\024\061\021\062\045\063\041" +
    "\064\051\065\101\066\074\001\002\000\004\106\167\001" +
    "\002\000\030\011\uffba\067\uffba\070\uffba\071\uffba\072\uffba" +
    "\073\uffba\074\uffba\075\uffba\076\uffba\077\uffba\106\uffba\001" +
    "\002\000\006\041\055\103\053\001\002\000\006\041\055" +
    "\103\053\001\002\000\012\011\uffc2\076\uffc2\077\uffc2\106" +
    "\uffc2\001\002\000\012\011\uffc3\076\uffc3\077\uffc3\106\uffc3" +
    "\001\002\000\006\010\uffe5\012\uffe5\001\002\000\004\104" +
    "\200\001\002\000\014\055\023\056\025\057\026\060\024" +
    "\061\021\001\002\000\004\104\uffe7\001\002\000\004\102" +
    "\ufff7\001\002\000\004\002\001\001\002\000\004\113\233" +
    "\001\002\000\006\013\202\020\206\001\002\000\010\004" +
    "\uffff\005\uffff\013\uffff\001\002\000\006\013\ufffc\020\ufffc" +
    "\001\002\000\004\101\211\001\002\000\004\002\000\001" +
    "\002\000\006\013\ufffd\020\ufffd\001\002\000\004\021\214" +
    "\001\002\000\006\021\214\102\232\001\002\000\006\021" +
    "\uffa0\102\uffa0\001\002\000\004\103\215\001\002\000\004" +
    "\113\216\001\002\000\006\104\uff9d\110\uff9d\001\002\000" +
    "\006\104\221\110\220\001\002\000\004\113\230\001\002" +
    "\000\004\022\222\001\002\000\004\101\223\001\002\000" +
    "\004\023\224\001\002\000\004\107\225\001\002\000\004" +
    "\112\226\001\002\000\004\102\227\001\002\000\006\021" +
    "\uff9f\102\uff9f\001\002\000\006\104\uff9e\110\uff9e\001\002" +
    "\000\006\021\uffa1\102\uffa1\001\002\000\004\002\uffa2\001" +
    "\002\000\004\101\234\001\002\000\004\014\235\001\002" +
    "\000\004\107\343\001\002\000\004\102\342\001\002\000" +
    "\004\015\240\001\002\000\004\107\340\001\002\000\004" +
    "\016\242\001\002\000\004\107\311\001\002\000\004\017" +
    "\244\001\002\000\004\107\246\001\002\000\004\102\uffaf" +
    "\001\002\000\004\101\247\001\002\000\004\031\250\001" +
    "\002\000\004\107\253\001\002\000\004\102\252\001\002" +
    "\000\004\102\uffab\001\002\000\004\103\255\001\002\000" +
    "\004\110\263\001\002\000\014\055\023\056\025\057\026" +
    "\060\024\061\021\001\002\000\006\104\uffa6\110\uffa6\001" +
    "\002\000\006\104\261\110\260\001\002\000\014\055\023" +
    "\056\025\057\026\060\024\061\021\001\002\000\004\110" +
    "\uffa8\001\002\000\006\104\uffa7\110\uffa7\001\002\000\004" +
    "\032\264\001\002\000\004\107\265\001\002\000\004\112" +
    "\266\001\002\000\004\110\267\001\002\000\004\033\270" +
    "\001\002\000\004\107\271\001\002\000\004\103\273\001" +
    "\002\000\004\110\301\001\002\000\014\062\045\063\041" +
    "\064\051\065\101\066\074\001\002\000\006\104\277\110" +
    "\276\001\002\000\006\104\uffa3\110\uffa3\001\002\000\014" +
    "\062\045\063\041\064\051\065\101\066\074\001\002\000" +
    "\004\110\uffa5\001\002\000\006\104\uffa4\110\uffa4\001\002" +
    "\000\004\034\302\001\002\000\004\107\303\001\002\000" +
    "\004\112\304\001\002\000\004\110\305\001\002\000\004" +
    "\035\306\001\002\000\004\107\307\001\002\000\004\112" +
    "\310\001\002\000\004\102\uffa9\001\002\000\004\101\312" +
    "\001\002\000\004\024\314\001\002\000\004\102\337\001" +
    "\002\000\004\107\315\001\002\000\004\112\316\001\002" +
    "\000\004\110\317\001\002\000\004\025\320\001\002\000" +
    "\004\107\321\001\002\000\004\112\322\001\002\000\004" +
    "\110\323\001\002\000\004\026\324\001\002\000\004\107" +
    "\325\001\002\000\004\112\326\001\002\000\004\110\327" +
    "\001\002\000\004\027\330\001\002\000\004\107\331\001" +
    "\002\000\004\112\332\001\002\000\004\110\333\001\002" +
    "\000\004\030\334\001\002\000\004\107\335\001\002\000" +
    "\004\112\336\001\002\000\004\102\uffaa\001\002\000\004" +
    "\017\uffac\001\002\000\004\112\341\001\002\000\004\016" +
    "\uffad\001\002\000\006\013\uffb0\020\uffb0\001\002\000\004" +
    "\103\344\001\002\000\004\113\345\001\002\000\004\110" +
    "\346\001\002\000\004\113\347\001\002\000\004\104\350" +
    "\001\002\000\004\015\uffae\001\002\000\004\101\352\001" +
    "\002\000\004\006\353\001\002\000\004\107\356\001\002" +
    "\000\004\102\355\001\002\000\010\004\ufff8\005\ufff8\013" +
    "\ufff8\001\002\000\014\062\045\063\041\064\051\065\101" +
    "\066\074\001\002\000\004\007\360\001\002\000\004\107" +
    "\361\001\002\000\004\103\362\001\002\000\004\010\364" +
    "\001\002\000\006\010\364\012\372\001\002\000\072\036" +
    "\100\037\073\040\036\041\055\042\072\043\064\044\070" +
    "\045\075\046\050\047\047\050\104\051\057\054\040\055" +
    "\023\056\025\057\026\060\024\061\021\062\045\063\041" +
    "\064\051\065\101\066\074\100\054\103\053\105\065\111" +
    "\061\112\046\001\002\000\006\010\uffe2\012\uffe2\001\002" +
    "\000\006\011\367\077\141\001\002\000\014\062\045\063" +
    "\041\064\051\065\101\066\074\001\002\000\004\110\371" +
    "\001\002\000\006\010\uffe8\012\uffe8\001\002\000\014\062" +
    "\045\063\041\064\051\065\101\066\074\001\002\000\004" +
    "\104\375\001\002\000\006\010\uffe3\012\uffe3\001\002\000" +
    "\004\102\ufff6\001\002\000\004\104\uffe6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\374\000\014\002\010\003\007\004\004\006\005\007" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\203\006\005\007" +
    "\006\022\202\045\204\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\015\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\012\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\014" +
    "\031\016\032\001\001\000\006\016\173\020\174\001\001" +
    "\000\002\001\001\000\044\005\036\012\042\013\055\023" +
    "\043\024\076\025\075\026\065\027\041\030\061\031\066" +
    "\033\102\034\051\037\062\040\101\041\057\043\034\044" +
    "\070\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\005\151\012\042" +
    "\013\055\042\150\001\001\000\040\005\036\012\042\013" +
    "\055\025\147\026\065\027\041\030\061\031\066\033\102" +
    "\034\051\037\062\040\101\041\057\043\034\044\070\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\044\005\036\012\042" +
    "\013\055\023\136\024\076\025\075\026\065\027\041\030" +
    "\061\031\066\033\102\034\051\037\062\040\101\041\057" +
    "\043\034\044\070\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\032\132\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\005\036\012\042\013\055\033\102" +
    "\040\107\001\001\000\014\005\036\012\042\013\055\033" +
    "\102\040\106\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\035\111\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\040\005\036\012\042\013\055\025" +
    "\120\026\065\027\041\030\061\031\066\033\102\034\051" +
    "\037\062\040\101\041\057\043\034\044\070\001\001\000" +
    "\002\001\001\000\004\035\122\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\030\135\031\066\037\062\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\030\061\031" +
    "\066\037\062\044\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\042\005\036\012\042\013\055\024\141\025\075" +
    "\026\065\027\041\030\061\031\066\033\102\034\051\037" +
    "\062\040\101\041\057\043\034\044\070\001\001\000\002" +
    "\001\001\000\004\035\143\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\005" +
    "\154\012\042\013\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\012\156\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\034\163\035\161\036\162\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\005\165\012\042\013\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\034\051\041\057\043\172\001" +
    "\001\000\010\034\051\041\057\043\171\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\176\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\045" +
    "\207\061\206\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\062\211\063\212\001\001\000\004\063\230\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\064\216\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\046\235\047\236\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\050\240\001" +
    "\001\000\002\001\001\000\004\051\242\001\001\000\002" +
    "\001\001\000\004\053\244\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\054\250\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\055\253\001\001\000\002\001\001\000\006\012\255" +
    "\056\256\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\261\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\057\271\001\001\000\002\001\001\000\006\013\274\060" +
    "\273\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\277\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\052\312" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\353" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\356\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\015\362\017\364\001" +
    "\001\000\006\017\373\021\372\001\001\000\044\005\036" +
    "\012\042\013\055\023\365\024\076\025\075\026\065\027" +
    "\041\030\061\031\066\033\102\034\051\037\062\040\101" +
    "\041\057\043\034\044\070\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\367\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\375\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= lista_estrategias lista_partidas principal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_estrategias ::= lista_estrategias estrategia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_estrategias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_estrategias ::= estrategia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_estrategias",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // lista_partidas ::= lista_partidas partida 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // lista_partidas ::= partida 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // estrategia ::= estrategia_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // estrategia ::= estrategia_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // estrategia_mago ::= MAGE ID LLAVE_A cuerpo_mago LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia_mago",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // estrategia_guerrero ::= WARRIOR ID LLAVE_A cuerpo_guerrero LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estrategia_guerrero",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // cuerpo_mago ::= INITIAL DOS_PUNTOS accion_mago RULES DOS_PUNTOS CORCHETE_A lista_reglas_mago regla_else_mago CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cuerpo_mago",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // cuerpo_guerrero ::= INITIAL DOS_PUNTOS accion_guerrero RULES DOS_PUNTOS CORCHETE_A lista_reglas_guerrero regla_else_guerrero CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cuerpo_guerrero",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // accion ::= accion_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // accion ::= accion_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // accion_mago ::= ARCANE_BOLT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // accion_mago ::= FIREBALL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // accion_mago ::= MAGIC_BARRIER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // accion_mago ::= HEALING_RUNE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // accion_mago ::= MEDITATE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_mago",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // accion_guerrero ::= SLASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // accion_guerrero ::= HEAVY_STRIKE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // accion_guerrero ::= SHIELD_BLOCK 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // accion_guerrero ::= WAR_CRY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // accion_guerrero ::= REST 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("accion_guerrero",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // regla_mago ::= IF condicion THEN accion_mago COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_mago",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // regla_guerrero ::= IF condicion THEN accion_guerrero COMA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_guerrero",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // regla_else_mago ::= ELSE accion_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_else_mago",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // regla_else_guerrero ::= ELSE accion_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("regla_else_guerrero",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_reglas_mago ::= lista_reglas_mago regla_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_mago",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_reglas_mago ::= regla_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_mago",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_reglas_guerrero ::= lista_reglas_guerrero regla_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_guerrero",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_reglas_guerrero ::= regla_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_reglas_guerrero",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion ::= condicion OR condicion_and 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= condicion_and 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion_and ::= condicion_and AND condicion_not 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_and",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion_and ::= condicion_not 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_and",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion_not ::= NOT condicion_not 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_not",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion_not ::= condicion_base 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_not",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion_base ::= comparacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion_base ::= PAR_A condicion PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operador_comparacion ::= IGUAL_IGUAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operador_comparacion ::= DIFERENTE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operador_comparacion ::= MAYOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // operador_comparacion ::= MENOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operador_comparacion ::= MAYOR_IGUAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operador_comparacion ::= MENOR_IGUAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("operador_comparacion",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // estado_entero ::= ROUND_NUMBER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // estado_entero ::= TOTAL_ROUNDS 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // estado_entero ::= SELF_HEALTH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // estado_entero ::= OPPONENT_HEALTH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // estado_entero ::= SELF_RESOURCE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // estado_entero ::= OPPONENT_RESOURCE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // estado_entero ::= SELF_SCORE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // estado_entero ::= OPPONENT_SCORE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("estado_entero",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // valor_numerico ::= estado_entero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_numerico",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // valor_numerico ::= ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_numerico",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // valor_numerico ::= RANDOM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_numerico",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // valor_numerico ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_numerico",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // valor_numerico ::= funcion_entera 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_numerico",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // comparacion ::= expresion_numerica operador_comparacion expresion_numerica 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // comparacion ::= valor_accion IGUAL_IGUAL valor_accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // comparacion ::= valor_accion DIFERENTE valor_accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // comparacion ::= valor_lista IGUAL_IGUAL valor_lista 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // comparacion ::= valor_lista DIFERENTE valor_lista 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparacion",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // historial ::= SELF_HISTORY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // historial ::= OPPONENT_HISTORY 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("historial",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // funcion_accion ::= GET_MOVE PAR_A historial COMA ENTERO PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_accion",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // funcion_accion ::= LAST_MOVE PAR_A historial PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_accion",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // funcion_lista ::= GET_LAST_N_MOVES PAR_A historial COMA ENTERO PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_lista",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // fuente_historial ::= historial 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente_historial",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // fuente_historial ::= funcion_lista 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fuente_historial",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // funcion_entera ::= GET_MOVES_COUNT PAR_A fuente_historial COMA accion PAR_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_entera",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // valor_accion ::= accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_accion",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // valor_accion ::= funcion_accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_accion",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // lista_acciones ::= CORCHETE_A elementos_acciones CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // elementos_acciones ::= elementos_acciones COMA accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // elementos_acciones ::= accion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // valor_lista ::= lista_acciones 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_lista",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // valor_lista ::= funcion_lista 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_lista",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expresion_numerica ::= expresion_numerica MENOS valor_numerico 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion_numerica ::= valor_numerico 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion_numerica",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // partida ::= MATCH ID LLAVE_A cuerpo_partida LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("partida",35, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // cuerpo_partida ::= jugadores rondas scoring bonuses 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cuerpo_partida",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // jugadores ::= PLAYERS DOS_PUNTOS CORCHETE_A ID COMA ID CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("jugadores",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // rondas ::= ROUNDS DOS_PUNTOS ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("rondas",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // scoring ::= SCORING DOS_PUNTOS LLAVE_A lista_scoring LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("scoring",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // bonuses ::= BONUSES DOS_PUNTOS LLAVE_A lista_bonuses LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bonuses",41, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // lista_scoring ::= DAMAGE_POINT DOS_PUNTOS ENTERO COMA HEALING_POINT DOS_PUNTOS ENTERO COMA SUCCESSFUL_DEFENSE DOS_PUNTOS ENTERO COMA VICTORY_BONUS DOS_PUNTOS ENTERO COMA FAILED_ACTION_PENALTY DOS_PUNTOS ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_scoring",40, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // lista_bonuses ::= MAGE_COMBO DOS_PUNTOS lista_acciones_mago COMA MAGE_COMBO_POINTS DOS_PUNTOS ENTERO COMA WARRIOR_COMBO DOS_PUNTOS lista_acciones_guerrero COMA WARRIOR_COMBO_POINTS DOS_PUNTOS ENTERO COMA LOW_HEALTH_VICTORY DOS_PUNTOS ENTERO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_bonuses",42, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // lista_acciones_mago ::= CORCHETE_A elementos_acciones_mago CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_mago",43, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // elementos_acciones_mago ::= elementos_acciones_mago COMA accion_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones_mago",44, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // elementos_acciones_mago ::= accion_mago 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones_mago",44, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // lista_acciones_guerrero ::= CORCHETE_A elementos_acciones_guerrero CORCHETE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_acciones_guerrero",45, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // elementos_acciones_guerrero ::= elementos_acciones_guerrero COMA accion_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones_guerrero",46, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // elementos_acciones_guerrero ::= accion_guerrero 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("elementos_acciones_guerrero",46, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // principal ::= MAIN LLAVE_A cuerpo_principal LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("principal",47, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // cuerpo_principal ::= cuerpo_principal instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cuerpo_principal",48, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // cuerpo_principal ::= instruccion_run 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("cuerpo_principal",48, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // instruccion_run ::= RUN CORCHETE_A lista_partidas_run CORCHETE_C WITH LLAVE_A SEED DOS_PUNTOS ENTERO LLAVE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_run",49, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // lista_partidas_run ::= lista_partidas_run COMA ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas_run",50, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // lista_partidas_run ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_partidas_run",50, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
