
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOR_IGUAL = 56;
  public static final int VICTORY_BONUS = 21;
  public static final int REST = 52;
  public static final int MAGE = 2;
  public static final int OPPONENT_RESOURCE = 37;
  public static final int SELF_HEALTH = 34;
  public static final int SHIELD_BLOCK = 50;
  public static final int MAYOR = 57;
  public static final int ROUNDS = 11;
  public static final int DIFERENTE = 54;
  public static final int OPPONENT_SCORE = 39;
  public static final int RANDOM = 42;
  public static final int HEALING_RUNE = 46;
  public static final int ARCANE_BOLT = 43;
  public static final int RUN = 15;
  public static final int HEAVY_STRIKE = 49;
  public static final int GET_MOVE = 28;
  public static final int SELF_HISTORY = 40;
  public static final int MAGE_COMBO_POINTS = 24;
  public static final int IGUAL_IGUAL = 53;
  public static final int PAR_C = 68;
  public static final int PAR_A = 67;
  public static final int NOT = 62;
  public static final int CORCHETE_C = 66;
  public static final int MATCH = 9;
  public static final int CORCHETE_A = 65;
  public static final int INITIAL = 4;
  public static final int THEN = 7;
  public static final int DOS_PUNTOS = 69;
  public static final int DAMAGE_POINT = 18;
  public static final int FIREBALL = 44;
  public static final int LLAVE_C = 64;
  public static final int LLAVE_A = 63;
  public static final int GET_LAST_N_MOVES = 31;
  public static final int COMA = 70;
  public static final int ENTERO = 72;
  public static final int SEED = 17;
  public static final int SLASH = 48;
  public static final int WARRIOR_COMBO = 25;
  public static final int HEALING_POINT = 19;
  public static final int DECIMAL = 71;
  public static final int LAST_MOVE = 29;
  public static final int SCORING = 12;
  public static final int LOW_HEALTH_VICTORY = 27;
  public static final int ELSE = 8;
  public static final int MENOS = 59;
  public static final int MENOR = 58;
  public static final int ROUND_NUMBER = 32;
  public static final int EOF = 0;
  public static final int MEDITATE = 47;
  public static final int PLAYERS = 10;
  public static final int MAIN = 14;
  public static final int OR = 61;
  public static final int RULES = 5;
  public static final int error = 1;
  public static final int MAGE_COMBO = 23;
  public static final int FAILED_ACTION_PENALTY = 22;
  public static final int SELF_RESOURCE = 36;
  public static final int IF = 6;
  public static final int ID = 73;
  public static final int WARRIOR = 3;
  public static final int WARRIOR_COMBO_POINTS = 26;
  public static final int WAR_CRY = 51;
  public static final int OPPONENT_HEALTH = 35;
  public static final int BONUSES = 13;
  public static final int GET_MOVES_COUNT = 30;
  public static final int MAGIC_BARRIER = 45;
  public static final int TOTAL_ROUNDS = 33;
  public static final int AND = 60;
  public static final int SUCCESSFUL_DEFENSE = 20;
  public static final int SELF_SCORE = 38;
  public static final int OPPONENT_HISTORY = 41;
  public static final int WITH = 16;
  public static final int MAYOR_IGUAL = 55;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAGE",
  "WARRIOR",
  "INITIAL",
  "RULES",
  "IF",
  "THEN",
  "ELSE",
  "MATCH",
  "PLAYERS",
  "ROUNDS",
  "SCORING",
  "BONUSES",
  "MAIN",
  "RUN",
  "WITH",
  "SEED",
  "DAMAGE_POINT",
  "HEALING_POINT",
  "SUCCESSFUL_DEFENSE",
  "VICTORY_BONUS",
  "FAILED_ACTION_PENALTY",
  "MAGE_COMBO",
  "MAGE_COMBO_POINTS",
  "WARRIOR_COMBO",
  "WARRIOR_COMBO_POINTS",
  "LOW_HEALTH_VICTORY",
  "GET_MOVE",
  "LAST_MOVE",
  "GET_MOVES_COUNT",
  "GET_LAST_N_MOVES",
  "ROUND_NUMBER",
  "TOTAL_ROUNDS",
  "SELF_HEALTH",
  "OPPONENT_HEALTH",
  "SELF_RESOURCE",
  "OPPONENT_RESOURCE",
  "SELF_SCORE",
  "OPPONENT_SCORE",
  "SELF_HISTORY",
  "OPPONENT_HISTORY",
  "RANDOM",
  "ARCANE_BOLT",
  "FIREBALL",
  "MAGIC_BARRIER",
  "HEALING_RUNE",
  "MEDITATE",
  "SLASH",
  "HEAVY_STRIKE",
  "SHIELD_BLOCK",
  "WAR_CRY",
  "REST",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "MENOS",
  "AND",
  "OR",
  "NOT",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "PAR_A",
  "PAR_C",
  "DOS_PUNTOS",
  "COMA",
  "DECIMAL",
  "ENTERO",
  "ID"
  };
}

